### ISSUE TITLE
Can not download image datasets

### ISSUE THREAD

**Issue by wangqiang9** [mtli/PhotoSketch#16]
Hello, I can not download the image, the error is `File "/root/anaconda3/envs/sketch/lib/python3.9/urllib/request.py", line 641, in http_error_default  raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 403: Forbidden` 
I am from Chinese Mainland, Maybe access to this area has been banned. Can you share the data with me? My email is `wanqqiang@bupt.edu.cn`
Thank you very much!

**Comment by wangqiang9** [comment]
I have solved this problem. Thank you a lot！

**Comment by Palavra1** [comment]
I am also from Chinese Mainland, may i ask how did you solve it?  modify the crawler code?
