### ISSUE TITLE
problem using pertained model

### ISSUE THREAD

**Issue by wanlipeng** [mtli/PhotoSketch#3]
I choose the  resent_9_block ,I seems the generator model error...
RuntimeError: Error(s) in loading state_dict for ResnetGenerator
Missing key(s) in state_dict: "model.1.bias", "model.4.bias", "model.7.bias", "model.10.conv_block.1.bias", "model.10.conv_block.6.bias", "model.11.conv_block.1.bias", "model.11.conv_block.6.bias....

**Comment by mtli** [comment]
Thanks for trying out the code! Could you provide more information about the error? By default, the model uses resnet_9blocks as the backbone. Are you attempting to change that?

**Comment by mtli** [comment]
Closing due to no feedback. Feel free to reopen it.
