### ISSUE TITLE
PSA: Colour output should be clipped if using the pretrained model for generating datasets

### ISSUE THREAD

**Issue by 9of9** [mtli/PhotoSketch#4]
Something I didn't think to check for a while, but the model actually leaves a lot of residual data in off-white colours that aren't visible to the human eye, but which will be picked up on by other ML algorithms.

![image](https://user-images.githubusercontent.com/31524061/52205738-fa758f00-286f-11e9-912f-60125e1baf06.png)

In this example, if you adjust the levels, there is actually more data encoded about his hairline than is first apparent:

![image](https://user-images.githubusercontent.com/31524061/52205777-24c74c80-2870-11e9-8a71-1b9c139bc919.png)

**Comment by mtli** [comment]
Thanks for trying out our method! Our training data are prepared that the strokes are rendered with anti-aliasing, which means that it is not a binary image. This is intended to create the soft looking for the strokes. However, in your example, clearly the algorithm over smooths the strokes, producing too many non zero outputs. This might be a result of the alignment issue in the ground truth. A recommended solution is to either threshold the output image to produce a binary image, or remove pixels with intensity smaller than a threshold.

**Comment by 9of9** [comment]
Yep, adjusting levels on the output images solved the issue entirely - I just wanted to make other users aware that this can happen, since it can be difficult to spot by the naked eye until it's too late! :D
