### ISSUE TITLE
Output to paths instead of pixel image?

### ISSUE THREAD

**Issue by SamBahrami** [mtli/PhotoSketch#8]
Is there a way to output a list of paths to draw/plot instead of outputting a pixel image? Or an SVG or something?

I am trying to use this model to do kind of semantic contour/edge detection on images, that I could then plot using a robot arm on paper. 

Thanks

**Comment by mtli** [comment]
Generating stroke paths is beyond this work. But if you need paths output, you can try segmenting the bitmap strokes at each junction and generating a path from the top left to bottom right for each segment (or any order you like).

**Comment by jin-wong1031** [comment]
> Is there a way to output a list of paths to draw/plot instead of outputting a pixel image? Or an SVG or something?
> 
> I am trying to use this model to do kind of semantic contour/edge detection on images, that I could then plot using a robot arm on paper.
> 
> Thanks

Have you found the way to generate stroke paths?

**Comment by SamBahrami** [comment]
> > Is there a way to output a list of paths to draw/plot instead of outputting a pixel image? Or an SVG or something?
> > I am trying to use this model to do kind of semantic contour/edge detection on images, that I could then plot using a robot arm on paper.
> > Thanks
> 
> Have you found the way to generate stroke paths?

One way I have been able to do this is to use a library called [potrace](https://en.wikipedia.org/wiki/Potrace), and then convert the paths it generates into a list of list of paths, and finally scale those to fit on my output medium. Unfortunately I can't share the code for this.

**Comment by jin-wong1031** [comment]
> > > Is there a way to output a list of paths to draw/plot instead of outputting a pixel image? Or an SVG or something?
> > > I am trying to use this model to do kind of semantic contour/edge detection on images, that I could then plot using a robot arm on paper.
> > > Thanks
> > 
> > 
> > Have you found the way to generate stroke paths?
> 
> One way I have been able to do this is to use a library called [potrace](https://en.wikipedia.org/wiki/Potrace), and then convert the paths it generates into a list of list of paths, and finally scale those to fit on my output medium. Unfortunately I can't share the code for this.

That's ok, thanks.
